// <auto-generated />
using System;
using Hospital_Management_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Migrations
{
    [DbContext(typeof(HospitalDBContext))]
    [Migration("20241207183338_AddPatientsTable")]
    partial class AddPatientsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Data.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("PersonId");

                    b.ToTable("Patients", (string)null);

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PatientId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            PatientId = 3,
                            PersonId = 3
                        },
                        new
                        {
                            PatientId = 4,
                            PersonId = 4
                        },
                        new
                        {
                            PatientId = 5,
                            PersonId = 1001
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Data.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Address = "ryk",
                            BirthDate = new DateOnly(1990, 1, 1),
                            Email = "alyan@gmail.com",
                            Gender = "M",
                            Name = "Alyan",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            PersonId = 2,
                            Address = "A-Block ryk",
                            BirthDate = new DateOnly(2002, 1, 1),
                            Email = "ali@gmail.com",
                            Gender = "M",
                            Name = "Ali",
                            PhoneNumber = "12345677790"
                        },
                        new
                        {
                            PersonId = 3,
                            Address = "B-Block ryk",
                            BirthDate = new DateOnly(2003, 1, 1),
                            Email = "zafar@gmail.com",
                            Gender = "M",
                            Name = "zafar",
                            PhoneNumber = "03045677790"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Data.Patient", b =>
                {
                    b.HasOne("Hospital_Management_System.Data.Person", "Person")
                        .WithMany("Patients")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Patient_Person_PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Hospital_Management_System.Data.Person", b =>
                {
                    b.Navigation("Patients");
                });
#pragma warning restore 612, 618
        }
    }
}
